name: Auto Reply to Pull Requests

on:
  pull_request:

jobs:
  auto_reply:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run script
        id: script
        run: |
          modified_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "$modified_files"

          comment=$(python .github/scoring.py "${modified_files}")

          echo "$comment"
          echo "$comment" > comment.txt

      - name: Comment on pull request
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment.txt
          comment_tag: "Scoring"
