name: Auto Reply to Pull Requests

on:
  pull_request:

jobs:
  auto_reply:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run script
        id: script
        run: |
          modified_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "$modified_files"
          modified_folder=$(dirname "$(echo "${modified_files}" | head -n 1)")
          echo "$modified_folder"

          comment=$(python .github/scoring.py "${modified_folder}")

          echo "$comment"
          echo "comment=$comment" | tee -a $GITHUB_OUTPUT

      - name: Comment on pull request
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ steps.script.outputs.comment }}
            })
